### ISSUE TITLE
randomize yöne giden kutu

### ISSUE THREAD

**Issue by Sayeimehtap** [Alkan-09/Box-animation#2]
- en üsttte button tanımlanması ve text içeriği random yöne kutuyu gönder yazsın
- buttona tıklandığında kutu üste, aşağıi sağa ya da sola random bir yön seçip gitsin
- button da kutunun gittiği yön bilgisi yazsın örnek "kutu sağa gidiyor"

**Comment by Alkan-09** [comment]
Kusursuz olmadı fakat gene de bitti :)
